<?php
/**
 * Directory Structure Scanner
 * 
 * Script location : {here}/test/scan/directory.php
 * Scans           : {here}/                 (two levels up from the script)
 * Output folder   : {here}/test/scan/log/   (same folder as this script)
 */

// ============================================================
// CONFIGURATION (relative to this script's location)
// ============================================================

// __DIR__            = {here}/test/scan
// dirname(__DIR__)   = {here}/test
// dirname(dirname(__DIR__)) = {here}    ← the folder we want to scan

$scanDirectory = dirname(__DIR__, 2) . DIRECTORY_SEPARATOR;   // {here}/
$outputDir     = __DIR__ . DIRECTORY_SEPARATOR . 'log' . DIRECTORY_SEPARATOR;  // {here}/test/scan/log/

// ============================================================
// SETUP & VALIDATION
// ============================================================

// Create output directory if it doesn't exist
if (!is_dir($outputDir)) {
    if (!mkdir($outputDir, 0755, true)) {
        die("❌ Error: Failed to create output directory: " . $outputDir . PHP_EOL);
    }
}

// Generate timestamped output filename (with microseconds)
$timestamp  = date('Y-m-d_H-i-s-u');
$outputFile = $outputDir . $timestamp . '_directory.txt';

// Verify the scan directory exists
if (!is_dir($scanDirectory)) {
    die("❌ Error: Scan directory does not exist: " . $scanDirectory . PHP_EOL);
}

if (!is_readable($scanDirectory)) {
    die("❌ Error: Scan directory is not readable: " . $scanDirectory . PHP_EOL);
}

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Format bytes into a human-readable string
 */
function formatBytes($bytes, $precision = 2)
{
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    $bytes = max($bytes, 0);
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
    $pow = min($pow, count($units) - 1);
    $bytes /= pow(1024, $pow);
    return round($bytes, $precision) . ' ' . $units[$pow];
}

/**
 * Recursively scan a directory and build a tree string
 */
function scanDirectory($dir, $prefix = '', $output = '', $exclude = [])
{
    $items = array_diff(scandir($dir), ['.', '..'], $exclude);

    $directories = [];
    $files = [];

    foreach ($items as $item) {
        $path = $dir . DIRECTORY_SEPARATOR . $item;
        if (is_dir($path)) {
            $directories[] = $item;
        } else {
            $files[] = $item;
        }
    }

    // Sort case-insensitively
    natcasesort($directories);
    natcasesort($files);

    $sortedItems = array_merge(array_values($directories), array_values($files));
    $totalItems  = count($sortedItems);
    $counter     = 0;

    foreach ($sortedItems as $item) {
        $counter++;
        $path    = $dir . DIRECTORY_SEPARATOR . $item;
        $isLast  = ($counter === $totalItems);

        $connector = $isLast ? '└── ' : '├── ';
        $extension = $isLast ? '    ' : '│   ';

        if (is_dir($path)) {
            $output .= $prefix . $connector . '[DIR]  ' . $item . '/' . PHP_EOL;

            if (is_readable($path)) {
                $output = scanDirectory($path, $prefix . $extension, $output, $exclude);
            } else {
                $output .= $prefix . $extension . '     [Permission Denied]' . PHP_EOL;
            }
        } else {
            $size         = @filesize($path);
            $readableSize = ($size !== false) ? formatBytes($size) : 'N/A';
            $output      .= $prefix . $connector . '[FILE] ' . $item . ' (' . $readableSize . ')' . PHP_EOL;
        }
    }

    return $output;
}

// ============================================================
// BUILD REPORT
// ============================================================

$output  = '';
$output .= str_repeat('=', 70) . PHP_EOL;
$output .= 'DIRECTORY STRUCTURE REPORT' . PHP_EOL;
$output .= str_repeat('=', 70) . PHP_EOL;
$output .= 'Scanned Path : ' . $scanDirectory . PHP_EOL;
$output .= 'Output Path  : ' . $outputFile . PHP_EOL;
$output .= 'Scan Date    : ' . date('Y-m-d H:i:s') . PHP_EOL;
$output .= 'PHP Version  : ' . PHP_VERSION . PHP_EOL;
$output .= 'Generated By : ' . __FILE__ . PHP_EOL;
$output .= str_repeat('=', 70) . PHP_EOL . PHP_EOL;

// Root folder name ({here}/)
$rootName = basename(rtrim($scanDirectory, '/\\'));
$output  .= '[ROOT] ' . $rootName . '/' . PHP_EOL;

// Recursively scan
$output .= scanDirectory($scanDirectory, '', '', []);

// ============================================================
// SUMMARY
// ============================================================

$output .= PHP_EOL . str_repeat('=', 70) . PHP_EOL;
$output .= 'SUMMARY' . PHP_EOL;
$output .= str_repeat('=', 70) . PHP_EOL;

$dirCount  = 0;
$fileCount = 0;
$totalSize = 0;

$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($scanDirectory, RecursiveDirectoryIterator::SKIP_DOTS),
    RecursiveIteratorIterator::SELF_FIRST
);

foreach ($iterator as $item) {
    if ($item->isDir()) {
        $dirCount++;
    } else {
        $fileCount++;
        $totalSize += $item->getSize();
    }
}

$output .= 'Total Directories : ' . $dirCount . PHP_EOL;
$output .= 'Total Files       : ' . $fileCount . PHP_EOL;
$output .= 'Total Size        : ' . formatBytes($totalSize) . PHP_EOL;
$output .= str_repeat('=', 70) . PHP_EOL;

// ============================================================
// WRITE OUTPUT FILE
// ============================================================

if (file_put_contents($outputFile, $output) !== false) {
    echo "✅ Directory structure logged successfully!" . PHP_EOL;
    echo "📄 Output file : " . $outputFile . PHP_EOL;
    echo "📊 Directories : {$dirCount}" . PHP_EOL;
    echo "📊 Files       : {$fileCount}" . PHP_EOL;
    echo "📊 Total Size  : " . formatBytes($totalSize) . PHP_EOL;
} else {
    echo "❌ Error: Failed to write to " . $outputFile . PHP_EOL;
    exit(1);
}

// ============================================================
// OPTIONAL: AUTO-CLEANUP OLD REPORTS (older than 7 days)
// ============================================================
$cleanupDays = 7;
$now         = time();
$oldFiles    = glob($outputDir . '*_directory.txt');
if ($oldFiles) {
    foreach ($oldFiles as $file) {
        if (is_file($file) && ($now - filemtime($file)) > ($cleanupDays * 86400)) {
            @unlink($file);
        }
    }
}