<?php

namespace App\Controllers;

use App\Models\UsersLogSummary;
use Core\Controller;
use Core\Response;
use Core\Session;

/**
 * Generated by make:model UsersLogSummary. Follows the same shape as PostController:
 * findOrFail() for 404s, $this->validate() for input, Session::flash() for
 * one-time messages, and a single form.php view shared by create and edit.
 */
class UsersLogSummaryController extends Controller
{
    private const RULES = [
        'log_id' => '',
        'name' => '',
        'email' => 'email',
        'Activity' => '',
    ];


    public function index(): Response
    {
        $page = (int) $this->request->query('page', 1);
        $result = UsersLogSummary::paginate(10, $page, [], 'id DESC');

        return $this->view('UsersLogSummary/index', ['title' => 'UsersLogSummary'] + $result);
    }

    public function create(): Response
    {
        return $this->view('UsersLogSummary/form', [
            'title' => 'New UsersLogSummary',
            'item'  => null,
        ]);
    }

    public function store(): Response
    {
        $item = UsersLogSummary::create($this->validate(self::RULES));

        Session::flash('success', 'UsersLogSummary created.');

        return $this->redirect('/UsersLogSummary/' . $item->id);
    }

    public function show($id): Response
    {
        $item = UsersLogSummary::findOrFail($id);

        return $this->view('UsersLogSummary/show', [
            'title' => 'UsersLogSummary details',
            'item'  => $item,
        ]);
    }

    public function edit($id): Response
    {
        $item = UsersLogSummary::findOrFail($id);

        return $this->view('UsersLogSummary/form', [
            'title' => 'Edit UsersLogSummary',
            'item'  => $item,
        ]);
    }

    public function update($id): Response
    {
        $item = UsersLogSummary::findOrFail($id);
        $item->update($this->validate(self::RULES));

        Session::flash('success', 'UsersLogSummary updated.');

        return $this->redirect('/UsersLogSummary/' . $item->id);
    }

    public function destroy($id): Response
    {
        UsersLogSummary::findOrFail($id)->delete();

        Session::flash('success', 'UsersLogSummary deleted.');

        return $this->redirect('/UsersLogSummary');
    }
}
