<?php

namespace App\Controllers;

use App\Models\UsersLog;
use Core\Controller;
use Core\Response;
use Core\Session;

/**
 * Generated by make:model UsersLog. Follows the same shape as PostController:
 * findOrFail() for 404s, $this->validate() for input, Session::flash() for
 * one-time messages, and a single form.php view shared by create and edit.
 */
class UsersLogController extends Controller
{
    private const RULES = [
        'UserID' => 'numeric',
        'Activity' => '',
    ];


    public function index(): Response
    {
        $page = (int) $this->request->query('page', 1);
        $result = UsersLog::paginate(10, $page, [], 'id DESC');

        return $this->view('UsersLog/index', ['title' => 'UsersLog'] + $result);
    }

    public function create(): Response
    {
        return $this->view('UsersLog/form', [
            'title' => 'New UsersLog',
            'item'  => null,
        ]);
    }

    public function store(): Response
    {
        $item = UsersLog::create($this->validate(self::RULES));

        Session::flash('success', 'UsersLog created.');

        return $this->redirect('/UsersLog/' . $item->id);
    }

    public function show($id): Response
    {
        $item = UsersLog::findOrFail($id);

        return $this->view('UsersLog/show', [
            'title' => 'UsersLog details',
            'item'  => $item,
        ]);
    }

    public function edit($id): Response
    {
        $item = UsersLog::findOrFail($id);

        return $this->view('UsersLog/form', [
            'title' => 'Edit UsersLog',
            'item'  => $item,
        ]);
    }

    public function update($id): Response
    {
        $item = UsersLog::findOrFail($id);
        $item->update($this->validate(self::RULES));

        Session::flash('success', 'UsersLog updated.');

        return $this->redirect('/UsersLog/' . $item->id);
    }

    public function destroy($id): Response
    {
        UsersLog::findOrFail($id)->delete();

        Session::flash('success', 'UsersLog deleted.');

        return $this->redirect('/UsersLog');
    }
}
