<?php

namespace App\Controllers;

use App\Models\UsersLogView;
use Core\Controller;
use Core\Response;

/**
 * Generated by make:view UsersLogView. Read-only — UsersLogView is backed by a
 * SQL VIEW, so this only lists data; there's no create, edit or delete.
 */
class UsersLogViewController extends Controller
{
    public function index(): Response
    {
        return $this->view('users_log_view/index', [
            'title' => 'Users Log View',
            'rows'  => UsersLogView::all(),
        ]);
    }
}
